sudo: false
language: ruby
os:
  - linux
rvm:
  - 2.0.0
  - 2.1
  - 2.2.4
  - 2.2.4-clang
  - 2.3.0
  - 2.3.0-clang
  - 2.4.2
  - 2.4.2-clang
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem install bundler
cache: bundler
