language: ruby

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head

branches:
  only:
    - master

script: bundle exec rake spec

before_install:
 - gem update bundler

matrix:
  allow_failures:
    - rvm: ruby-head
