AllCops:
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - vendor/**/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
