language: ruby

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - ruby-head
  - jruby-9.1.5.0

sudo: false

branches:
  only:
    - master

gemfile:
  - Gemfile

script: bundle exec rake spec

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0

notifications:
  webhooks: http://td-beda.herokuapp.com/travisci_callback
