rvm:
 - 1.9.3
 - 2.0.0
 - 2.1
 - 2.2
 - 2.3.1
 - 2.4.0
 - ruby-head

gemfile:
 - Gemfile
 - Gemfile.v0.12

before_install: gem update bundler
script: bundle exec rake spec

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile.v0.12
    - rvm: 2.3.1
      gemfile: Gemfile.v0.12
    - rvm: 2.4.0
      gemfile: Gemfile.v0.12
    - rvm: ruby-head
      gemfile: Gemfile.v0.12
